# version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount local /data folder to /app/data in the container
      - ./models:/app/models  # Mount local /models folder to /app/models in the container
    environment:
      - PYTHONUNBUFFERED=1

  tests:
    build: .
    volumes:
      - ./data:/app/data  # Mount local /data folder to /app/data in the container
      - ./models:/app/models  # Mount local /models folder to /app/models in the container
    command: npx promptfoo eval --output ./data/promptfoo_test_output.json --max-concurrency 2  # Run promptfoo test suite
    depends_on:
      - chatbot
