providers:
  - id: file://../backend/custom_provider.py
tests: file://../testing/chatbot_tests.csv
prompts: 
  - "{{input}}"
defaultTest:
  options:
    provider:
      id: file://backend/custom_eval_provider.py
    factuality:
      subset: 1 # Score for category A (default: 1)
      superset: 1 # Score for category B (default: 1)
      agree: 1 # Score for category C (default: 1)
      disagree: 0 # Score for category D (default: 0)
      differButFactual: 1 # Score for category E (default: 1)