providers:
  - id: file://../backend/custom_provider.py
prompts: 
  - "{{input}}"
tests: file://../testing/chatbot_tests.csv
defaultTest:
  options:
    provider:
      id: file://backend/custom_eval_provider.py