providers:
  - id: file://../backend/custom_provider.py
tests:
  - vars:
      prompt: "Why is the sky blue?"
    assert:
      - type: icontains
        value: "I don't know the answer"
      - type: factuality
        value: "I don't know the answer."
defaultTest:
  options:
    provider:
      id: file://backend/custom_eval_provider.py